object Versions {
    const val COMPOSE_ACTIVITY = "1.5.1"
    const val COMPOSE_NAVIGATION = "2.5.3"
    const val COMPOSE_ICONS = "1.4.3"
    const val COMPOSE_BOM = "2022.10.00"
    const val JUNIT = "4.13.2"
    const val JUNIT_EXT = "1.1.5"
    const val EXPRESSO_CORE = "3.5.1"
    const val CORE_KTX = "1.8.0"
    const val APP_COMPAT = "1.6.1"
    const val MATERIAL = "1.9.0"
    const val LIFECYCLE_RUNTIME_KTX = "2.3.1"
    const val TRUTH = "1.1.3"
    const val MOCKK = "1.13.5"
    const val FIREBASE_BOM = "32.0.0"
}